language: php

php:
  - 7.1

install:
  - travis_retry composer install --no-interaction --no-suggest
  - composer show --installed

branches:
  only: master

before_script:
  - travis_retry composer self-update

script:
  - php $TRAVIS_BUILD_DIR/vendor/bin/phpcs --standard=psr2 $TRAVIS_BUILD_DIR/src/ -n
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit $TRAVIS_BUILD_DIR/tests/