language: php

php:
  - 7.0
  - 7.1
  - 7.2

install:
  - composer install

branches:
  only: master

before_script:
  - travis_retry composer self-update

script:
  - php $TRAVIS_BUILD_DIR/vendor/bin/phpcs --standard=psr2 $TRAVIS_BUILD_DIR/src/ -n
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit $TRAVIS_BUILD_DIR/tests/